### ISSUE TITLE
Abuse of function arguments to trigger update

### ISSUE THREAD

**Issue by brunnerh** [skayo/svelte-tiny-virtual-list#14]
This is just a suggestion regarding how the size recalculation is triggered in this line:

```js
$: if (mounted) recomputeSizes(0, height, width, stickyIndices); // call scroll.reset;
```

At first glance this looks like a mistake because the function only accepts one argument.
I would instead write it like this:

```js
$: {
  height, width, stickyIndices;
  if (mounted) recomputeSizes(0); // call scroll.reset;
}
```

[REPL example of this approach](https://svelte.dev/repl/e4c72465f43748588dd87b3e2bb2dc10?version=3.46.6)

**Comment by skayo** [comment]
Indeed, this is much cleaner!
