### ISSUE TITLE
smooth scroll when using scrollToIndex ? 

### ISSUE THREAD

**Issue by anotherempty** [skayo/svelte-tiny-virtual-list#16]
Can you add a scroll animation when using scrollToIndex ? and if possible allow an easing function to be passed as a parameter for the scrolling animation ?

**Comment by skayo** [comment]
This will require a few changes, but I will probably add this feature when I find the time!

**Comment by skayo** [comment]
Added in 2.0.5 (ce19972)! 
Just set `scrollToBehaviour` to `auto` (it's `instant` by default to maintain backwards compatibility) 

Let me know if there's any problems!
