### ISSUE TITLE
Support for use of animate: directive

### ISSUE THREAD

**Issue by jeremyjacob** [skayo/svelte-tiny-virtual-list#18]
I love the animate directive and Svelte's `flip` function. Is there a way to use that with the `VirtualList`?

**Comment by skayo** [comment]
I'm guessing you mean something like this:
```
<!-- When `list` is reordered the animation will run-->
{#each list as item, index (item)}
	<li animate:flip>{item}</li>
{/each}
```

And it _might_ be possible, there's an #each-directive inside the component after all, but I don't have many hopes that it works well... I'll try it out!
