### ISSUE TITLE
ids do not have a stability property.

### ISSUE THREAD

**Issue by FunMiles** [Skayo/svelte-tiny-virtual-list#2]
First, thanks for creating this version of VirtualList. The 'sticky' feature is something I have been wanting.

Now the problem I am facing:

When a scroll list comes from a dynamic database and items are added or removed, a stability property is needed. That is to say for a given item, the loop `id` should always bind to the same item. From reading the source code, the `id` right now is `item.index` which when a database inserts new item, is not stable.

A possible solution:
`svelte-virtual-list` has the same issue. However I've addressed it in that code very simply and the same could be done here.
First add:
```javascript
    export let indexing;
```
and use it in the loop:
```jsx
        <div class="virtual-list-inner" style={innerStyle}>
		{#each items as item (indexing ? indexing(item.index) : item.index)}
			<slot name="item" style={item.style} index={item.index} />
		{/each}
	</div>
```

Alternatively, the call to `indexing` could be done inside the `refresh` function.

**Comment by Skayo** [comment]
A bit late, but here you are :)
