### ISSUE TITLE
It's possible to know what items are rendered?

### ISSUE THREAD

**Issue by RubenPX** [skayo/svelte-tiny-virtual-list#28]
I'm trying to search some function or prop that shows me items or indexes are rendered

Someling like: `rendered indexes 23 to 27`.

**Comment by inzanez** [comment]
@RubenPX how about using the event `itemsUpdated` listed in the documentation? I guess that should do.

`itemsUpdated - Fired when the visible items are updated
detail Props:
start: number - Index of the first visible item
end: number - Index of the last visible item
`
