### ISSUE TITLE
TypeError when using scrollToAlignment or scrollDirection

### ISSUE THREAD

**Issue by www-chique** [Skayo/svelte-tiny-virtual-list#3]
So I'm doing a minimal setup of the VirtualList.
When I try to use the scrollToAlignment , like `let scrollToAlignment  = 'center';`
And subsequently use it in the VirtualList as a property, I get the following error.
![image](https://user-images.githubusercontent.com/29447216/109726447-c436a500-7bd8-11eb-8b30-267583fcd1c5.png)

**Comment by Skayo** [comment]
Should be fixed by #7
