### ISSUE TITLE
estimatedItemSize - details

### ISSUE THREAD

**Issue by inzanez** [skayo/svelte-tiny-virtual-list#9]
Hi

first of all, many thanks for that great component! :-) Works really nice and smooth.

I do have a question about the 'estimateItemSize' though:
I was under the impression that this was used to calculate the total scroll-height. So,...that it should basically match `itemCount * itemSize` in case of equal height items.

If that's right, I also thought that this would prevent that growing scrollbar during scrolling. It seems that as items are being recomputed, my scrollbar grows. So I tried to use `estimatedItemSize` as described above. But that gives me another weird behavior (scrolling to the bottom after a few initial correctly scrolled items). So maybe I got that totally wrong,...:-)

**Comment by skayo** [comment]
Any updates on this? I'd like to close this issue

**Comment by inzanez** [comment]
Of course,...I haven't found what exactly it does, so....I am ignoring it for now ;-)
